### ISSUE TITLE
Error messages in Logg

### ISSUE THREAD

**Issue by KnatteAnka** [IStrikeboomI/CobblestoneSemantics#6]
since last update i get allot of this message:
```
[00:40:09 WARN]: Skipping BlockEntity with id cobblestonesemantics:lava_generator
[00:40:09 ERROR]: Failed to load data for block entity cobblestonesemantics:lava_generator
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.m_7260_(net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, net.minecraft.world.level.block.state.BlockState, int)" because the return value of "Strikeboom.cobblestonesemantics.guis.blockentities.LavaGeneratorBlockEntity.access$300(Strikeboom.cobblestonesemantics.guis.blockentities.LavaGeneratorBlockEntity)" is null
	at Strikeboom.cobblestonesemantics.guis.blockentities.LavaGeneratorBlockEntity$2.onEnergyChanged(LavaGeneratorBlockEntity.java:49) ~[cobblestonesemantics-1.18.1-1.3.jar%2355!/:1.3]
	at Strikeboom.cobblestonesemantics.guis.blockentities.energystorage.CobblestoneSemanticsEnergyStorage.setEnergy(CobblestoneSemanticsEnergyStorage.java:21) ~[cobblestonesemantics-1.18.1-1.3.jar%2355!/:1.3]
	at Strikeboom.cobblestonesemantics.guis.blockentities.LavaGeneratorBlockEntity.m_142466_(LavaGeneratorBlockEntity.java:75) ~[cobblestonesemantics-1.18.1-1.3.jar%2355!/:1.3]
	at net.minecraft.world.level.block.entity.BlockEntity.m_155246_(BlockEntity.java:122) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.world.level.block.entity.BlockEntity.m_155241_(BlockEntity.java:120) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_196900_(ChunkSerializer.java:410) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_62952_(LevelChunk.java:417) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.server.level.ChunkMap.m_199335_(ChunkMap.java:622) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-4.0.26.jar%2329!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar%2329!/:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-4.0.26.jar%2329!/:?]
	at net.minecraft.server.level.ChunkMap.m_199332_(ChunkMap.java:606) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:58) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:530) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:538) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:132) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.world.level.Level.m_6522_(Level.java:170) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:122) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.world.level.Level.m_6325_(Level.java:165) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.world.level.Level.m_46745_(Level.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.world.level.Level.m_7702_(Level.java:529) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkNodeGraph.invalidate(NetworkNodeGraph.java:35) ~[refinedstorage-1.10.0.jar%23131!/:1.10.0]
	at com.refinedmods.refinedstorage.apiimpl.network.Network.update(Network.java:206) ~[refinedstorage-1.10.0.jar%23131!/:1.10.0]
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onLevelTick(NetworkListener.java:17) ~[refinedstorage-1.10.0.jar%23131!/:1.10.0]
	at net.minecraftforge.eventbus.ASMEventHandler_704_NetworkListener_onLevelTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPostWorldTick(ForgeEventFactory.java:866) ~[forge-1.18.1-39.0.79-universal.jar%23163!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:874) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23159!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[00:40:09 WARN]: Skipping BlockEntity with id cobblestonesemantics:lava_generator
```

**Comment by IStrikeboomI** [comment]
Fixed with f73c3dbb54839411b0da6c8b6a9703e707576fe5
